baseURL = "https://xzhseh.github.io/"
copyright = "© Michael Xu"
languageCode = "en-us"
title = "Michael Xu"
theme = "hugo-ink"

# Code Highlight
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 10 # articales per page

[params]
	subtitle = "「An Creator」"

	avatar = "https://avatars.githubusercontent.com/u/91381303"

	featherIconsCDN = true

	mode = "auto" # automatically change the mode

[[params.social]]
	icon = "github"
	name = "Github"
	url = "https://github.com/xzhseh"

[[params.social]]
	icon = "twitter"
	name = "Twitter"
	url = "https://twitter.com/CallMeVerta"

[[menu.main]]
	name = "About"
	url = "/about"
	weight = 1

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 2

[[menu.main]]
	name = "All posts"
	url = "/posts"
	weight = 3

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 4


